title: "Albert Feijao Stories"
description: "Stories from a young imagination"
theme: jekyll-theme-midnight

# If using a custom domain such as www.albertfeijao.com
# keep baseurl empty.
url: "https://www.albertfeijao.com"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  stories:
    output: true
    permalink: /stories/:name/

exclude:
  - README.md
  - LICENSE
